### ISSUE TITLE
Letters skipped in landscape

### ISSUE THREAD

**Issue by VeronicaHowes** [mobify/tozee#2]
Two or three letters skipped when in landscape so that you can't navigate to the letters by clicking.

**Comment by VeronicaHowes** [comment]
An example from a project: https://mobify.atlassian.net/browse/VIA-176

**Comment by donnielrt** [comment]
@Bielousov do we still need a fix for the issue, and would you know what the potential fix is?

**Comment by Bielousov** [comment]
Fixed in v.1.0.0, improved in v.1.1.0
Now when tapping between letters plugin detects missing letters if any and navigates to them.
In v. 1.1.0 the detection method became a bit more precise accounting on the fact that first and last letters have less overlapping surface then others.
